"""added rel on usesssr

Revision ID: 0f9eee81f2b2
Revises: 667795a892cc
Create Date: 2026-05-03 21:26:48.173259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f9eee81f2b2'
down_revision: Union[str, Sequence[str], None] = '667795a892cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'observation_list', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observation_list', type_='foreignkey')
    # ### end Alembic commands ###
