"""cascade observation

Revision ID: 72c52ebcb0b6
Revises: 0f9eee81f2b2
Create Date: 2026-05-04 00:09:58.851452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72c52ebcb0b6'
down_revision: Union[str, Sequence[str], None] = '0f9eee81f2b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('observation_list_user_id_fkey'), 'observation_list', type_='foreignkey')
    op.create_foreign_key(None, 'observation_list', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'observation_list', type_='foreignkey')
    op.create_foreign_key(op.f('observation_list_user_id_fkey'), 'observation_list', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
