"""add rating and number_of_reviews to SMA

Revision ID: cd4609d319a5
Revises: 1be473300e94
Create Date: 2026-05-02 13:29:12.857600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd4609d319a5'
down_revision: Union[str, Sequence[str], None] = '1be473300e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('SMA', sa.Column('number_of_reviews', sa.Integer(), nullable=True))
    op.add_column('SMA', sa.Column('rating', sa.Float(), nullable=False))
    op.create_unique_constraint('_user_movie_uc', 'reviews', ['user_id', 'movie_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_user_movie_uc', 'reviews', type_='unique')
    op.drop_column('SMA', 'rating')
    op.drop_column('SMA', 'number_of_reviews')
    # ### end Alembic commands ###
